# Generated by Django 5.2 on 2025-06-14 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leiloes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('descricao', models.TextField(max_length=100, verbose_name='Descricao')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField()),
                ('valorInicial', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Valor Inicial')),
                ('valorAtual', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Valor Atual')),
                ('valorFinal', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Valor Final')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Lance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lances', to='leiloes.item')),
            ],
            options={
                'verbose_name': 'Lance',
                'verbose_name_plural': 'Lances',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
