# Generated by Django 5.2 on 2025-06-17 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leiloes', '0003_item_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='data_fim',
            field=models.DateTimeField(null=True, verbose_name='Data Final'),
        ),
        migrations.AlterField(
            model_name='item',
            name='data_inicio',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data Inicial'),
        ),
    ]
