# Generated by Django 5.2 on 2025-06-20 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leiloes', '0004_alter_item_data_fim_alter_item_data_inicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lance',
            options={},
        ),
    ]
