# Generated by Django 5.2 on 2025-06-20 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leiloes', '0005_alter_lance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lance',
            options={'ordering': ['id'], 'verbose_name': 'Lance', 'verbose_name_plural': 'Lances'},
        ),
    ]
