# Generated by Django 5.2 on 2025-06-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leiloes', '0006_alter_lance_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='valorFinal',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Final'),
        ),
    ]
